### ISSUE TITLE
Code release?

### ISSUE THREAD

**Issue by pratik18v** [zhenxingjian/Propagating_Covariance#1]
Hi,
Can you let us know when you plan to release the code for the CIFAR10 and ImageNet experiments?

Thank you
Pratik

**Comment by zhenxingjian** [comment]
I'm sorry for this late reply, I just realized that I have not published the code for ImageNet though I remember I did.
I just published the code for ImageNet, and Cifar-10 is exactly the same as ImageNet, so I didn't include the Cifar-10 training here.

Hope this will help.
